#!/usr/bin/env bash

# This script allows easy SSH connections to every host managed by Ansible.

set -e
set -o pipefail
set -o nounset

if [ "${#}" -lt 1 ]; then
	echo "Usage: ${0} <ssh args> <hostname>"
	exit 1
fi

hostname="${!#}"
# Remove the last parameter
set -- "${@:1:$(($#-1))}"

# Fetch infos about host
conn="$(ansible localhost -m debug -a "msg={{ hostvars[\"${hostname}\"].ansible_user }}@{{ hostvars[\"${hostname}\"].ansible_host }}" | \
	grep '^\s*"msg":' | \
	cut -d'"' -f4)"

# Connect
exec ssh "${@}" "${conn}"
